site_name: Iguana $VERSION Documentation

extra:
  version: $RELEASE_VERSION
  release_version: $RELEASE_VERSION
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dice-group/IGUANA

repo_url: https://github.com/dice-group/IGUANA
repo_name: dice-group/IGUANA

edit_uri: ""

theme: 
  #name: 'readthedocs'
  custom_dir: 'images/'
  name: material 
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate

  include_search_page: false
  search_index_only: true

  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: logo_white.png
  favicon: IGUANA_logo.png
  icon:
    logo: logo
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: deep purple
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - macros


color: "#82BDC3"

nav:
  - "General":
    - "About": "README.md"
  
  - "Configuration":
      - "Overview": "configuration/overview.md"
      - "Tasks": "configuration/tasks.md"
      - "Workers": "configuration/workers.md"
      - "Queries": "configuration/queries.md"
      - "Response Body Processing": "configuration/response_body_processor.md"
      - "Language Processor": "configuration/language_processor.md"
      - "Result Storage": "configuration/storages.md"
      - "Metrics": "configuration/metrics.md"
      - "RDF Results": "configuration/rdf_results.md"
  - "Javadocs":
    - "Javadocs": "http://iguana-benchmark.eu/javadoc/latest/"
