name: Workflow Test

on:
  pull_request:
    branches:
      - develop

jobs:
  find_version:
    name: Find Release Version
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.step_find.outputs.RELEASE_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: 'Find velease version'
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
        id: step_find

  deploy_docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: find_version
    env:
      RELEASE_VERSION: ${{ needs.find_version.outputs.RELEASE_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Find Ontology Version
        run: echo "ONTOLOGY_VERSION=$(grep 'versionIRI' schema/iguana.owx | grep -Po '[0-9]+.[0-9]+.[0-9]+')" >> $GITHUB_OUTPUT
        id: find_ontology_version

      - name: Fetch Ontologies
        run: git fetch && git checkout origin/gh-pages ontology/
      - run: mkdir -p ontology/${{ steps.find_ontology_version.outputs.ONTOLOGY_VERSION }}
      - run: cp schema/iguana.owx ontology/${{ steps.find_ontology_version.outputs.ONTOLOGY_VERSION }}/iguana.owx
      - run: cp schema/iguana.owx ontology/iguana.owx
      - run: ls -l ontology/

#      - name: Deploy Ontology to FTP
#        run: lftp -u '$FTP_USER','$FTP_PASSWORD' files.dice-research.org << EOF
#              set ftp:ssl-protect-data true
#              cd vocab
#              mirror -R ontology/. iguana/
#              bye
#              EOF

