name: Workflow Test

on:
  push:
    branches:
      - feature/ahead-of-time-compiler

jobs:
  find_version:
    name: Find IGUANA version
    runs-on: ubuntu-latest
    outputs:
      iguana_version: ${{ steps.step_find.outputs.iguana_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: 'Find IGUANA version'
        run: echo "iguana_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
        id: step_find

  compile_jar:
    name: Compile Jar executable
    runs-on: ubuntu-latest
    needs: find_version
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: 'Compile jar'
        run: 'mvn -DskipTests package'
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'iguana-jar'
          path: 'target/'

  compile_native:
    name: Compile Native executable
    runs-on: ubuntu-latest
    needs: find_version
    steps:
      - uses: actions/checkout@v3
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          cache: 'maven'
      - name: 'Generate configuration files'
        run: './graalvm/generate-config.sh'
      - name: 'Compile native-binary'
        run: 'mvn -DskipTests package -Pnative'
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'iguana-native'
          path: 'target/iguana-${{ needs.find_version.outputs.iguana_version }}'

